---
abstract: 'test Net::LDAP code'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-LDAP-Server-Test
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 0
  IO::Select: 0
  IO::Socket: 0
  Net::LDAP: 0
  Net::LDAP::Server: 0.3
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-LDAP-Server-Test
  homepage: https://github.com/karpet/net-ldap-server-test
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/net-ldap-server-test
version: 0.19
