--- #YAML:1.0
name:                Net-LDAP-Server-Test
version:             0.07
abstract:            test Net::LDAP code
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Select:                    0
    IO::Socket:                    0
    Net::LDAP:                     0
    Net::LDAP::Server:             0.3
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
