--- #YAML:1.0
name:               Net-LDAP-Server-Test
version:            0.08
abstract:           test Net::LDAP code
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:         0
    IO::Select:         0
    IO::Socket:         0
    Net::LDAP:          0
    Net::LDAP::Server:  0.3
    Test::More:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
